const { load, ok, sleep, summary } = require('./lib');
(async () => {
  const A = await load(__dirname + '/../../build/tally-artifact.html', {});
  const { w, $, $$, click, T } = A;
  const back = async () => { w.dispatchEvent(new w.PopStateEvent('popstate', { state: null })); await sleep(15); };
  const h0 = w.history.length;
  click('[data-act="tab"][data-tab="jobs"]'); await sleep(10);
  click($$('[data-act="job:open"]')[0]); await sleep(15);
  ok(!$('#sheet').hidden && w.history.length === h0, 'in a browser tab (and in the artifact) nothing touches history');
  click('[data-act="sheet:close"]'); await sleep(10);
  w.TALLY_STANDALONE = true;
  click($$('[data-act="job:open"]')[0]); await sleep(20);
  ok(!$('#sheet').hidden && w.history.length === h0 + 1, 'installed app: opening a job adds one Back step');
  click('#sheet [data-act="call:cust"]'); await sleep(20);
  ok(!$('#call').hidden && w.history.length === h0 + 1, 'opening the call prompt on top adds nothing more');
  await back();
  ok($('#call').hidden && !$('#sheet').hidden, 'Back closes the call prompt, the job stays open');
  ok(w.history.length === h0 + 2, 'and keeps a Back step for the job');
  await back();
  ok($('#sheet').hidden, 'Back again closes the job');
  click('[data-act="more:open"]'); await sleep(20);
  await back();
  ok($('#more').hidden, 'Back closes the More sheet');
  click('[data-act="tab"][data-tab="chat"]'); await sleep(10); click('[data-act="chat:open"][data-t="all"]'); await sleep(20);
  await back();
  ok(/Everyone/.test($('#view').textContent) && !$('#msgList'), 'Back leaves a chat conversation for the list');
  ok(A.errors.length === 0, 'no errors (' + A.errors.slice(0, 3).join(' | ') + ')');
  process.exit(summary('back button') ? 1 : 0);
})().catch((e) => { console.error(e); process.exit(1); });
